# Pipeline defintion for Lint+Build+Test+Deploy* stages for PRs and Merges on "main"
# Only Deploy stage on successful merge INTO MAIN
name: CI/CD - Case Management API

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  id-token: write
  contents: read

# Pipeline job
jobs:
  lint-build-test-deploy:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.0.x"

      - name: Debug web app name
        run: echo "WEB_APP_NAME=${{ secrets.WEB_APP_NAME }}"
      - name: Debug resource group
        run: echo "RESOURCE_GROUP=${{ secrets.RESOURCE_GROUP }}"

      # -------------------
      # LINT STAGE
      # -------------------
      - name: Restore dependencies
        run: dotnet restore

      - name: Lint
        run: dotnet format --verify-no-changes
        continue-on-error: false

      # -------------------
      # BUILD STAGE
      # -------------------
      - name: Build
        run: dotnet build --configuration Release --no-restore

      # -------------------
      # TEST STAGE
      # -------------------
      - name: Run tests
        run: dotnet test --configuration Release --verbosity normal

      # -------------------
      # DEPLOY STAGE
      # -------------------
      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy API
        if: github.ref == 'refs/heads/main'
        run: |
          dotnet publish CaseManagement.Api/CaseManagement.Api.csproj -c Release -o publish

          az webapp deploy \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --name ${{ secrets.WEB_APP_NAME }} \
            --src-path publish \
            --type zip

      # Publish to Prod Database
      - name: Apply EF Migrations
        if: github.ref == 'refs/heads/main'
        run: dotnet ef database update --project CaseManagement.Api/CaseManagement.Api.csproj --configuration Release --environment Production
